package com.bankmega.multidb;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu May 28 10:36:50 ICT 2015
 * Generated source version: 2.1.3
 * 
 */
 
@WebService(targetNamespace = "http://multidb.service.ws.mega.com/ServiceMultiDb", name = "ServicePortTypeMultiDb")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ServicePortTypeMultiDb {

    @WebResult(name = "output", targetNamespace = "http://multidb.service.ws.mega.com/ServiceMultiDb", partName = "output")
    @WebMethod(action = "http://multidb.service.ws.mega.com/ServiceMultiDb/ServicePortTypeMultiDb/getServiceMultiDb")
    public OutputServiceMultiDb getServiceMultiDb(
        @WebParam(partName = "input", name = "input")
        InputServiceMultiDb input
    );
}
