
package com.bankmega.multidb;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.jws.soap.SOAPBinding.Style;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu May 28 10:36:50 ICT 2015
 * Generated source version: 2.1.3
 * 
 */

public final class ServicePortTypeMultiDb_ServicePortTypeBndPortMultiDb_Client {

    private static final QName SERVICE_NAME = new QName("http://multidb.service.ws.mega.com/ServiceMultiDb", "ws_MultiDb_Service");

    private ServicePortTypeMultiDb_ServicePortTypeBndPortMultiDb_Client() {
    }

    public static void main(String args[]) throws Exception {
        URL wsdlURL = WsMultiDbService.WSDL_LOCATION;
        if (args.length > 0) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsMultiDbService ss = new WsMultiDbService(wsdlURL, SERVICE_NAME);
        ServicePortTypeMultiDb port = ss.getServicePortTypeBndPortMultiDb();  
        
        {
        System.out.println("Invoking getServiceMultiDb...");
        com.bankmega.multidb.InputServiceMultiDb _getServiceMultiDb_input = null;
        com.bankmega.multidb.OutputServiceMultiDb _getServiceMultiDb__return = port.getServiceMultiDb(_getServiceMultiDb_input);
        System.out.println("getServiceMultiDb.result=" + _getServiceMultiDb__return);


        }

        System.exit(0);
    }

}
