
/*
 * 
 */

package com.bankmega.multidb;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 2.1.3
 * Thu May 28 10:36:50 ICT 2015
 * Generated source version: 2.1.3
 * 
 */


@WebServiceClient(name = "ws_MultiDb_Service", 
                  wsdlLocation = "http://10.14.18.159:8080/middleware/services/ServicePortTypeBndPortMultiDb?wsdl",
                  targetNamespace = "http://multidb.service.ws.mega.com/ServiceMultiDb") 
public class WsMultiDbService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://multidb.service.ws.mega.com/ServiceMultiDb", "ws_MultiDb_Service");
    public final static QName ServicePortTypeBndPortMultiDb = new QName("http://multidb.service.ws.mega.com/ServiceMultiDb", "ServicePortTypeBndPortMultiDb");
    static {
        URL url = null;
        try {
            url = new URL("http://10.14.18.159:8080/middleware/services/ServicePortTypeBndPortMultiDb?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://10.14.18.159:8080/middleware/services/ServicePortTypeBndPortMultiDb?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public WsMultiDbService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public WsMultiDbService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsMultiDbService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns ServicePortTypeMultiDb
     */
    @WebEndpoint(name = "ServicePortTypeBndPortMultiDb")
    public ServicePortTypeMultiDb getServicePortTypeBndPortMultiDb() {
        return super.getPort(ServicePortTypeBndPortMultiDb, ServicePortTypeMultiDb.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServicePortTypeMultiDb
     */
    @WebEndpoint(name = "ServicePortTypeBndPortMultiDb")
    public ServicePortTypeMultiDb getServicePortTypeBndPortMultiDb(WebServiceFeature... features) {
        return super.getPort(ServicePortTypeBndPortMultiDb, ServicePortTypeMultiDb.class, features);
    }

}
